import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header style={{ height: 50, backgroundColor: "LightGray" }}>
          header
        </header>
        {children}
        <footer style={{ height: 50, backgroundColor: "LightGray" }}>
          footer
        </footer>
      </body>
    </html>
  );
}
